# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  head_pan_joint:
    has_velocity_limits: true
    max_velocity: 6
    has_acceleration_limits: false
    max_acceleration: 0
  head_tilt_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: false
    max_acceleration: 0
  l_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: false
    max_acceleration: 0
  l_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_l_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_l_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_motor_screw_joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_motor_slider_joint:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_r_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_gripper_r_finger_tip_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: false
    max_acceleration: 0
  l_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.078
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  r_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 3.3
    has_acceleration_limits: false
    max_acceleration: 0
  r_forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.6
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.082
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.088
    has_acceleration_limits: false
    max_acceleration: 0
  r_upper_arm_roll_joint:
    has_velocity_limits: true
    max_velocity: 3.27
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_FFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_LFJ5:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_MFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ3:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_RFJ4:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ3:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ4:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  rh_THJ5:
    has_velocity_limits: true
    max_velocity: 4
    has_acceleration_limits: false
    max_acceleration: 0
  rh_WRJ1:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rh_WRJ2:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  torso_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.013
    has_acceleration_limits: false
    max_acceleration: 0